---
title: "Untitled"
author: "junghyun"
date: '2022 5 17 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 공휴일 정보를 API를 통해서 가져오기

```{r}
rm(list=ls())
library(glue)
library(XML)
library(stringr)
library(lubridate)
library(dplyr)
```

```{r}
api.key <- "WzPY1XSX%2BX7rgalcrRKQHOGSMG%2FCCotytqLjdMrl3PvKXhXc00G5Y0Fv4wObva75VD%2Fe5wQ32Gnd%2B0JeIwmItg%3D%3D"
url.format <- 'http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo?serviceKey={key}&solYear={year}&solMonth={month}'

holiday.request <- function(key, year, month) glue(url.format)

url <- holiday.request(api.key, "2022", "06")
data <- xmlToList(url)
items <- data$body$items

for (item in items){
  print(c(item$dateName,item$locdate))
}
```

### 원하는 연도의 전체 공휴일 정보 가져오기

```{r}
holidays <- data.frame(name=character(), date=character())

# request and read data
for(y in 2022){
  for(m in 1:12){
    data <- xmlToList(holiday.request(api.key, y, str_pad(m, 2, pad=0)))
    items <- data$body$items
    for(item in items){
      if(item$isHoliday == 'Y') holidays <- rbind(holidays, data.frame(item$dateName, item$locdate))
    }
  }
}

holidays
holiday_vec <- ymd(holidays$item.locdate)

### Lubridate 패키지를 사용해서, 공휴일중에, 토/일에 해당하는 날짜의 공휴일이 몇개인지, 계산
library(lubridate)
holidays$weekday = weekdays(holiday_vec)
holidays

holidays %>% filter(weekday == '토요일'| holidays$weekday == '일요일') %>% summarise(count=n())

```
### 공휴일 개수 count

```{r}
str(holidays) # 공휴일 날짜가 Character로 지정되어있음
holidays$item.locdate <- ymd(holidays$item.locdate)
holidays$wday <- wday(holidays$item.locdate,label = TRUE)

# 토/일에 있는 공휴일 개수
holidays %>% count(wday)

holidays %>% count(wday %in% c("일","토"))

holidays %>% summarise(bad_holiday = sum(wday %in% c("일","토")))
```


### 다른 방법

```{r}
library(httr)
library(jsonlite)

api_url <- "http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo"
api_key <- "1ZAWNkM7FJzRDet43qpUtoLPAMamljQE3xRyo2M4nByLkA4TtV0sPZ%2FIwfLXG0IJ2rkO8xw%2BlnRDSbnIcokGfw%3D%3D"

res <- GET(url = api_url,
           query = list(
             serviceKey = api_key %>% I(),
             solYear = "2022",
             solMonth = "06"
           ))

print(x=res)

json <- res %>% 
  content(as="text", encoding= "UTF-8") %>%
  fromJSON()

holidays_202206 <- json$response$body$items$item
```

### 월 별로? 가져오기

```{r}
get_holiday_by_month <- function(year = 2022, month = 6){
  api_url <-
    "http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo"
  api_key <-
    "1ZAWNkM7FJzRDet43qpUtoLPAMamljQE3xRyo2M4nByLkA4TtV0sPZ%2FIwfLXG0IJ2rkO8xw%2BlnRDSbnIcokGfw%3D%3D"
  
  # 호출 request 작성
  res <- GET(
    url = api_url,
    query = list(
      serviceKey = api_key %>% I(),
      solYear = year,
      solMonth = str_pad(month, 2, pad=0)
    )
  )
  
  # json을 list로 변환
  json <- res %>%
    content(as = "text", encoding = "UTF-8") %>%
    fromJSON()
  
  # 최종 결과물 dataframe으로 출력
  holiday_dat <- json$response$body$items
  # holiday_dat %>% select(dataName, locdate)
  
  return(holiday_dat)
}

tmp <- get_holiday_by_month(year = 2022, month = 4)
```



```{r}
# 연도별 1번째 방법
holidays <- data.frame(dataKind = character(),
                       name = character(),
                       isHoliday = character(),
                       date = character(),
                       seq = integer())

# request and read data
for(y in 2022) {
  for (m in 1:12) {
    dat <- get_holiday_by_month(year = y, month = m)
    if (dat != "") {
      holidays <- rbind(holidays,
                        dat$item)
    }
  }
}


for(y in 2022) {
  for (m in 1:12) {
    dat <- get_holiday_by_month(year = y, month = m)
    if (dat == "")
      next
    holidays <- rbind(holidays,
                      dat$item)
  }
}


# 연도별 2번째 방법
get_holiday_by_month <- function(year = 2022, month = 6){
  api_url <-
    "http://apis.data.go.kr/B090041/openapi/service/SpcdeInfoService/getRestDeInfo"
  api_key <-
    "1ZAWNkM7FJzRDet43qpUtoLPAMamljQE3xRyo2M4nByLkA4TtV0sPZ%2FIwfLXG0IJ2rkO8xw%2BlnRDSbnIcokGfw%3D%3D"
  
  # 호출 request 작성
  res <- GET(
    url = api_url,
    query = list(
      serviceKey = api_key %>% I(),
      solYear = year,
      solMonth = str_pad(month, 2, pad=0)
    )
  )
  
  # json을 list로 변환
  json <- res %>%
    content(as = "text", encoding = "UTF-8") %>%
    fromJSON()
  
  # 최종 결과물 dataframe으로 출력
  holiday_dat <- json$response$body$items
  
  if(holiday_dat == "") final_dat <- NULL else final_dat <- holiday_dat$item
   
  return(final_dat)
}

holiday_list <- lapply(1:12, get_holiday_by_month, year = 2022)

```


### 통행속도 api 가져오기
```{r}
# library (RCurl)

api.key <- "WzPY1XSX%2BX7rgalcrRKQHOGSMG%2FCCotytqLjdMrl3PvKXhXc00G5Y0Fv4wObva75VD%2Fe5wQ32Gnd%2B0JeIwmItg%3D%3D"
url.format <- "http://openapitraffic.daejeon.go.kr/traffic/rest/getTrafficInfoAll.do?serviceKey={key}&pageNo=1&num0fRows={numrows}"
link.speed.request <- function(key,numrows) glue(url.format)
url <- link.speed.request(api.key, 10)
data <- xmlToList(url)
View(data)
items <- data$body$`TRAFFIC-LIST` %>% bind_rows()

items

```

### 직접 URL을 바꿔주는 방법
```{r}
url <- "http://openapitraffic.daejeon.go.kr/traffic/rest/getTrafficInfoAll.do?serviceKey=WzPY1XSX%2BX7rgalcrRKQHOGSMG%2FCCotytqLjdMrl3PvKXhXc00G5Y0Fv4wObva75VD%2Fe5wQ32Gnd%2B0JeIwmItg%3D%3D&pageNo=1&num0fRows=30"
data <- xmlToList(url)
items <- data$body$`TRAFFIC-LIST` %>% bind_rows()
```

