---
title: "My first dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
# install.packages("flexdashboard")
library(flexdashboard)
library(sf)
library(leaflet)
library(RColorBrewer)
library(tidyverse)
```

```{r, include=FALSE}
# 데이터 읽기
hump <- st_read("./data/hump_pohang_final.shp")%>%
  st_set_precision(1e08)
road <- st_read("./data/road_pohang_split_final.shp")%>%
  st_set_precision(1e08)

# 위경도 좌표 변환
road_wgs <- road %>%
  st_set_precision(1e08) %>% 
  st_transform(4326)

hump_wgs <- hump %>% 
  st_transform(4326)

# 과속방지턱 인근 30m 도로 추출
# hump 주변 30m buffer
hump_buff_30m = hump %>% 
  st_buffer(dist = 30) %>%
  st_set_precision(1e08) %>% 
  st_transform(4326)

# st_intersection을 이용하여 buffer된 hump 기준으로 겹치는 road 추출
road_in_hump = st_intersection(road_wgs[1:100,], hump_buff_30m)%>% 
  st_transform(4326)
```

Column {data-width=350}
-----------------------------------------------------------------------

### 과속방지턱 범위 내의 도로 추출

```{r}
leaflet() %>% addTiles(group = "OSM (default)") %>% 
  addProviderTiles('CartoDB.Positron',
                   group = "CartoDB") %>% 
  addPolylines(data=road_wgs,col=~"grey", 
               group = "road",
               opacity = 1,
               weight = 1)%>%
  addPolylines(data=road_in_hump,
               col=~"orange", 
               group = "road_hump",
               opacity = 1,
               weight = 3,
               fillOpacity = 1)%>%
  addCircleMarkers(data=hump_wgs,
                   radius = 3,
                   color = "red",
                   stroke = F,
                   fillOpacity = 0.5, 
                   group = "hump") %>%
  # Layers control
  addLayersControl(
    baseGroups = c("CartoDB","OSM (default)"),
    overlayGroups = c("road", "road_hump", "hump"),
    options = layersControlOptions(collapsed = FALSE)
  )
```


Column {data-width=250}
-----------------------------------------------------------------------

### 도로 길이 분포

```{r}
ggplot(data=road %>% st_drop_geometry()) +
  geom_histogram(aes(x=length_1))
```

