---
title: "week_7a_exercise.Rmd"
author: "junghyun"
date: '2022 4 14 '
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 공간 연산 및 시각화 연습해보기

```{r}
library(sf)
library(tidyverse)
library(spData)
# install.packages("mapdeck")
library(mapdeck)
my_token <- Sys.getenv("MAPBOX_PUBLIC_TOKEN")
```

### Import data
crash_data : 영국 전체 사고 데이터
cycle_hire : 런던 자전거 대여소 위치
lnd:The boroughs of London - 런던과 인근지역 행정경계

```{r}
crash_data <- read.csv("https://git.io/geocompr-mapdeck") # 영국전체사고
crash_data
crash_data <- st_as_sf(crash_data %>% drop_na(),
                       coords = c("lng","lat"),
                       crs = st_crs(4326))
```

Question
런던 지역에서 사고가 발생한 위치로부터 반경 30m 이내에 있는 모든 자전거 대여소의 위치를 표시하고, 각 자전거 대여소마다 반경 30m 이내에 발생한 사고가 몇 건인지를 매핑하시오.

### 런던 지역 데이터만 뽑기

```{r}
london_polygon <- lnd %>% filter(ONS_INNER=="T")
crash_london <- crash_data[london_polygon,]
crash_london$crash_id <- 1:nrow(crash_london)
cycle_hire <- cycle_hire
```


### 1) Crash 주변 버퍼 만들기
```{r}
crash_buffer <- crash_london %>% 
  st_transform(27700) %>% 
  st_buffer(dist = 30) %>% 
  st_transform(4326) #mapedeck에서 쓰기위해 다시 위경도 좌표계로 바꿔줌
```

### 2) Crash 30m 버퍼를 기준으로 자전거대여소와 Join 하기
```{r}
crash_buffer_with_cycle <- crash_buffer %>% 
  st_join(cycle_hire, left = FALSE)
```

### 3) 자전거 대여소별로 사고발생건수 Count 하기

```{r}
crash_count_by_cycle <- crash_buffer_with_cycle %>% 
  st_drop_geometry() %>%  #공간정보제거 #메모리절약
  group_by(id) %>% # station_id별로 group_by
  summarise(crash_n=n())
```

### 4) 사고 Count 수를 원래 데이터에 붙이기
```{r}
cycle_hire_join <- cycle_hire %>% 
  left_join(crash_count_by_cycle, by="id") %>% 
  mutate(crash_n = ifelse(is.na(crash_n),0,crash_n))
# 사고가 주변에 안나서 Na 값 발생하므로 0으로 바꿔줌
cycle_hire_join[is.na(cycle_hire_join$crash_n),]$crash_n <- 0

tmp <- cycle_hire %>% 
  left_join(crash_count_by_cycle, by = "id")
```

### 5) 최종시각화
```{r}
ms = mapdeck_style("dark")

mapdeck(style = ms, pitch = 45, location = c(0,52),zoom = 4) %>% 
  add_polygon(data = lnd,
              layer_id = "polygon_layer",
              fill_opacity = 1) %>% 
  add_scatterplot(data = crash_london,
                  radius = 30,
                  fill_colour = "#DF171C",
                  layer_id = "Crash") %>% 
  add_scatterplot(data = cycle_hire,
                  layer_id = "Bike_Station",
                  radius = 50,
                  fill_colour = "#00FF00FF",)
```



## Import data
```{r}
library(tmaptools)
library(shinyjs)
palette_explorer()
```


## 런던 지역 데이터만 뽑기
```{r}
london_polygon <- lnd %>% filter(ONS_INNER=="T") 
crash_london <- crash_data[london_polygon,] 
crash_london$crash_id <- 1:nrow(crash_london)
cycle_hire <- cycle_hire
```

## 시각화
```{r}
ms = mapdeck_style("dark")

mapdeck(style = ms, pitch = 45, location = c(0, 52), zoom = 4) %>%
  add_polygon(data = lnd, 
              layer_id = "polygon_layer",
              fill_opacity = 1) %>%
  add_scatterplot(data=crash_london,
                  radius = 30,
                  fill_colour = "#DF171C",
                  layer_id="Crash") %>%
  add_scatterplot(data=cycle_hire,
                  layer_id="Bike_Station",
                  radius = 50,
                  fill_colour = "#00FF00FF")
```

